CREATE DATABASE DB_ECOMMERCE;

USE DB_ECOMMERCE;

CREATE TABLE TB_PRODUTOS(
ID BIGINT auto_increment,
TIPO VARCHAR (255),
PRECO DECIMAL,
MARCA VARCHAR (255),
COR VARCHAR (255),
TAMANHO VARCHAR (255),
primary key (ID)
);


INSERT INTO TB_PRODUTOS (TIPO,PRECO,MARCA,COR,TAMANHO) VALUES ('BATA','259.00','FARM','AZUL','P');
INSERT INTO TB_PRODUTOS (TIPO,PRECO,MARCA,COR,TAMANHO) VALUES ('CHAPEU','549.00','CHAPEU & ESTILO','BEGE','M');
INSERT INTO TB_PRODUTOS (TIPO,PRECO,MARCA,COR,TAMANHO) VALUES ('CAMISETA','98.00','HERING','BRANCA','M');
INSERT INTO TB_PRODUTOS (TIPO,PRECO,MARCA,COR,TAMANHO) VALUES ('CASACO','1989.00','THE NORTH FACE','VERDE','G');
INSERT INTO TB_PRODUTOS (TIPO,PRECO,MARCA,COR,TAMANHO) VALUES ('TENIS','939.99','NIKE','PRETO','41');
INSERT INTO TB_PRODUTOS (TIPO,PRECO,MARCA,COR,TAMANHO) VALUES ('CAMISETA','110.00','ROSA CHA','ROSA','M');
INSERT INTO TB_PRODUTOS (TIPO,PRECO,MARCA,COR,TAMANHO) VALUES ('SAIA','542.00','FARM','BRANCA','G');
INSERT INTO TB_PRODUTOS (TIPO,PRECO,MARCA,COR,TAMANHO) VALUES ('KIMONO','698.00','FARM','BRANCA','U');

SELECT * FROM TB_PRODUTOS WHERE PRECO > 500.00;
SELECT * FROM TB_PRODUTOS WHERE PRECO < 500.00;

UPDATE TB_PRODUTOS SET MARCA = "ROSA CHA" WHERE ID = 7;