CREATE DATABASE DB_ESCOLA;

USE DB_ESCOLA;

CREATE TABLE TB_ESTUDANTES(
ID BIGINT auto_increment,
NOME VARCHAR (255),
NOTA DECIMAL,
TURMA VARCHAR (255),
IDADE VARCHAR (255),
EMPENHO VARCHAR (255),
primary key (ID)
);


INSERT INTO TB_ESTUDANTES (NOME,NOTA,TURMA,IDADE,EMPENHO) VALUES ('TABATA','6.0','3B','17','INSATISFATORIO');
INSERT INTO TB_ESTUDANTES (NOME,NOTA,TURMA,IDADE,EMPENHO) VALUES ('MARCIO','4.5','3B','17','INSATISFATORIO');
INSERT INTO TB_ESTUDANTES (NOME,NOTA,TURMA,IDADE,EMPENHO) VALUES ('CAMILA','5.2','3B','17','INSATISFATORIO');
INSERT INTO TB_ESTUDANTES (NOME,NOTA,TURMA,IDADE,EMPENHO) VALUES ('PEDRO','9.8','3B','18','SATISFATORIO');
INSERT INTO TB_ESTUDANTES (NOME,NOTA,TURMA,IDADE,EMPENHO) VALUES ('SAMUEL','9.9','3B','18','SATISFATORIO');
INSERT INTO TB_ESTUDANTES (NOME,NOTA,TURMA,IDADE,EMPENHO) VALUES ('CAROLINA','4.3','3B','17','INSATISFATORIO');
INSERT INTO TB_ESTUDANTES (NOME,NOTA,TURMA,IDADE,EMPENHO) VALUES ('AISHA','8.9','3B','17','SATISFATORIO');
INSERT INTO TB_ESTUDANTES (NOME,NOTA,TURMA,IDADE,EMPENHO) VALUES ('MANUELA','10.0','3B','18','SATISFATORIO');

SELECT * FROM TB_ESTUDANTES WHERE NOTA > 7.0;
SELECT * FROM TB_ESTUDANTES WHERE NOTA < 7.0;

UPDATE TB_ESTUDANTES SET TURMA = "3A" WHERE ID = 5;